name = "codecrafters_http_server"
version = "1.0.0"

[dependencies]
gleam_stdlib = "== 0.54.0"
gleam_erlang = "== 0.34.0"
gleam_otp = "== 0.16.1"
glisten = "== 7.0.1"

[dev-dependencies]
gleeunit = "== 1.3.0"
