name = "codecrafters_http_server"
version = "1.0.0"

[dependencies]
gleam_stdlib = "== 0.54.0"
gleam_erlang = "== 0.34.0"
gleam_otp = "== 0.16.1"
glisten = "== 7.0.1"
argv = "== 1.0.2"
file_streams = "== 1.4.0"
filepath = "== 1.1.1"
simplifile = "== 2.0.0"

[dev-dependencies]
gleeunit = "== 1.3.0"
